=== CarlosDiazPando/XML-Esquemas/ejercicio 2/1_esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="apellidos" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="nota" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
              <xs:element name="edad" type="xs:integer" minOccurs="0" maxOccurs="1"/>
              <xs:element name="comentario" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
              <xs:attribute name="DNI">
                <xs:simpleType>
                  <xs:restriction base="xs:string"/>
                </xs:simpleType>
              </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CarlosDiazPando/XML-Esquemas/ejercicio 2/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/entornos/git/XML-Esquemas/ejercicio%202/1_esquema.xsd">
  <alumno DNI="99887766X">
    <nombre>Dario</nombre>  
    <apellidos>Fernández Álvarez</apellidos>
    <nota>3.50</nota>
    <edad>45</edad>
    <comentario>Necesita mejorar</comentario>
  </alumno>
  <alumno DNI="11223344A">
    <nombre>Luis</nombre>  
    <apellidos>Álvarez García</apellidos>
    <nota>6.75</nota>
    <edad>80</edad>
    <comentario>Copió de Darío y Pilar</comentario>
  </alumno>
  <alumno DNI="556677Z">
    <nombre>Pilar</nombre>  
    <apellidos>Rodríguez Menéndez</apellidos>
    <nota>8.25</nota>
    <comentario>Progresa adecuadamente</comentario>
  </alumno>
    <alumno DNI="66554433T">
    <nombre>Alfredo</nombre>  
    <apellidos>Martínez González</apellidos>
    <nota>0</nota>
    <edad>42</edad>
    <comentario>Estudió Universidad de Oviedo</comentario>
  </alumno>
</alumnos>
