=== CarlosDiazPando/XML-Esquemas/ejercicio 1_1/8_esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="mensajes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="mensaje" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="de" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="para" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="hora" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
              <xs:element name="texto">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="strong" type="xs:string" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> 
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CarlosDiazPando/XML-Esquemas/ejercicio 1_1/8_mensajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<mensajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/entornos/git/XML-Esquemas/ejercicio%201_1/8_esquema.xsd">
  <mensaje>
    <de>Pepe (pepe@example.com)</de>
    <para>Juan (juan@example.com)</para>
    <!--<hora>28/02/2011 17:48:23</hora> -->
    <hora>2011-02-28T17:48:23</hora>
    <texto>¿Hola, Juan, qué haces?</texto>
  </mensaje>
  <mensaje>
    <de>Juan (juan@example.com)</de>
    <para>Pepe (pepe@example.com)</para>
    <hora>2011-02-28T17:54:20.58</hora>
    <!-- <hora>2011-02-28T17:54:20</hora> -->
    <texto>Aquí, aprendiendo <strong>XML</strong></texto>
  </mensaje>
</mensajes>
